version: '3'

services:

  db: 
    image: postgres:16
    restart: always
    environment: 
      POSTGRES_PASSWORD: pass123+
    shm_size: 128mb
    ports: 
      - "5432:5432"
    volumes: 
      - postgresDB:/var/lib/postgresql/data

volumes:
  postgresDB: