name: Bild image app
on: push
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: ./src/Dockerfile
        push: false
        tags: otus/hw5:latest