name: buildProject
on: push
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
    - name: load branch
      uses: actions/checkout@v4
    - name: setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: install dependencies
      run: dotnet restore './src/PromoCodeFactory.WebHost/PromoCodeFactory.WebHost.csproj'
    - name: build
      run: dotnet build './src/PromoCodeFactory.WebHost/PromoCodeFactory.WebHost.csproj'
      
  build-image:
    runs-on: ubuntu-latest
    steps: 
    - name: load branch
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./src/Dockerfile
        push: false
        tags: otus/hw5:latest
