name: buildProject
on: push
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
    - name: load branch
      uses: actions/checkout@v4
    - name: setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x.x'
    - name: install dependencies
      run: dotnet restore './src/PromoCodeFactory.WebHost/PromoCodeFactory.WebHost.csproj'
    - name: build
      run: dotnet build './src/PromoCodeFactory.WebHost/PromoCodeFactory.WebHost.csproj'